name: whosthat
description: Flutter App for WhosThat

publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=2.18.5 <3.0.0"

dependencies:
    aws_iot_data_api: ^0.2.0
    flutter:
        sdk: flutter
    geolocator: ^9.0.2
    http: ^0.12.0
    timeago: ^3.2.2

dev_dependencies:
    flutter_lints: ^2.0.0
    flutter_test:
        sdk: flutter

flutter:
    uses-material-design: true
